### ISSUE TITLE
Bundle util classes into separate sub-project (working title "JCloudEE")

### ISSUE THREAD

**Issue by adersberger** [adersberger/cloud-native-zwitscher-jee#3]

**Comment by adersberger** [comment]
Not working with KumuluzEE due to only files in "classes" folder are scanned for CDI beans and the utils are heavily using this. Try this when WildFly Swarm is also possible.

**Comment by lreimer** [comment]
Seriously? This is quite a serious limitation of KumulzEE!

**Comment by adersberger** [comment]
my fault. forgot the beans.xml. Thx for getting me into this again.
